### ISSUE TITLE
Great Tool!

### ISSUE THREAD

**Issue by scrambled2** [s9roll7/ebsynth_utility#1]
Great tool. This is not an issue. More of a thought. Would it be possible to incorporate depth mapping as the mask somewhere in the pipeline? It tends to hold coherency for characters and the overall scene a bit stronger that just masking alone. Just a suggestion. I really appreciate the kickass tool!

**Comment by s9roll7** [comment]
Thank you for your suggestion.
I'll consider using depth mapping.

**Comment by s9roll7** [comment]
Added option to read depth map from the following paths.
/path_to_project_dir/video_key_depth/

**Comment by scrambled2** [comment]
Man this is rad. Thank you! Much appreciated.
