### ISSUE TITLE
stage1 video_frame and video_mask is empty.

### ISSUE THREAD

**Issue by nightroad1v1** [s9roll7/ebsynth_utility#127]
stage1

Skip frame extraction
Settings -> Mode=base, Device=cuda, Torchscript=disabled
mask created

completed.

video_frame and video_mask is empty.

**Comment by nightroad1v1** [comment]
换了一个文件存放地址和视频文件名又可以了

**Comment by jun665** [comment]
In fact, if the two directories already exist, the extraction frame is skipped, and deleting the two directories can also re-execute phase one
