### ISSUE TITLE
TypeError: Processed.__init__() missing 2 required positional arguments: 'p' and 'images_list'

### ISSUE THREAD

**Issue by probioallok** [s9roll7/ebsynth_utility#13]
Keep getting this error during stage 3 img2img. Double checked I had everything right. Any ideas?

**Comment by probioallok** [comment]
Blah on me. Didn't input project directory.

**Comment by Guwudao** [comment]
Hi @probioallok, I still get this error when I use [ebsynth_utility](https://github.com/s9roll7/ebsynth_utility) in img2img script. Do you know how to avoid this error?
![snapshot](https://github.com/user-attachments/assets/3160b6af-75a3-4af6-8412-28b92ece7b72)
