### ISSUE TITLE
This only works on windows？

### ISSUE THREAD

**Issue by loner233** [s9roll7/ebsynth_utility#14]
I saw `\`, `ffmpeg.exe`, etc in `stage1.py`, which means it doesn't seem to work on linux or Macos? Is there any plan to support?

**Comment by s9roll7** [comment]
It should only work on windows for now.
By the way, is there a way to use ebsynth on linux or mac?
If so, do you know if the .ebs file, which is the project file for ebsynth, is compatible with the windows version, even though it is in binary format?

**Comment by s9roll7** [comment]
fixed.
Maybe it will work on linux, mac, or colab, but I don't have the environment, so I haven't checked yet. The issue of how to run ebsynth itself in those environments is also not known

**Comment by vastava** [comment]
confirmed, works on mac on my end 💯

**Comment by hrach333** [comment]
I have an error in stage 7 in this formno out dir

**Comment by s9roll7** [comment]
Has ebsynth itself been successfully executed(stage 6)?
If it succeeded, out-XXXXX exists in the project directory.

**Comment by hrach333** [comment]
![image](https://user-images.githubusercontent.com/698064/224713757-4dd2fdc8-5956-4f08-9355-2b4ea10c164b.png)
these are the folders?

**Comment by hrach333** [comment]
they are there, but for some reason he does not see them `p = re.compile(r'.*\\out\\-([0-9]+)\\') p = re.compile(r'.*\\out\\-([0-9]+)\\')`  this code searches for folders with this name, and it takes the path to the folder from the file args.txt or from a web form where the project is specified?

**Comment by s9roll7** [comment]
ebsynth itself seems to be a success.
The implementation looks for out-XXXX in the directory specified in the Project directory.
By the way, what kind of environment is it? Is it Windows?

**Comment by s9roll7** [comment]
on second thought
p = re.compile(r'. *\\out\-([0-9]+)\\')
This code wouldn't work on anything but windows...

**Comment by s9roll7** [comment]
Probably fixed.

**Comment by hrach333** [comment]
I see a separate post has already appeared. Thanks, everything worked out now.

**Comment by hrach333** [comment]
> 



> ebsynth itself seems to be a success. The implementation looks for out-XXXX in the directory specified in the Project directory. By the way, what kind of environment is it? Is it Windows?
Yes, I almost guessed it)). This is Ubuntu with a Windows theme))

**Comment by hrach333** [comment]
> Probably fixed.

I understood that the problem lies somewhere here, since I am also a programmer, but I am not strong in python
