### ISSUE TITLE
Feature Request: Face crop resolution 

### ISSUE THREAD

**Issue by Echolink50** [s9roll7/ebsynth_utility#15]
First let me just say this extension is so phenomenal. I was using EBsynth separately and this makes life much easier. One issue I just ran into was using the extension with SDV2.1_768 model. The face crop always makes 512ish image. It's great for 1.5 and 512 models but it can't make a good face for the 768 model. I tried adjusting various setting but couldnt get it right. A separate slider to adjust the resolution of the face image would be great. One slider if it needs to keep the same ratio or 2 sliders if it doesnt. Thanks so much

**Comment by s9roll7** [comment]
Thanks for the suggestion.
I personally only use SD 1.5 and was not aware of it. We certainly need it.

**Comment by Echolink50** [comment]
Even if it's needed to keep the same 512x576 ratio, allowing sizes up to the 2048 would be great. Some models make terrible closeups at high resolutions, but some models make better faces at higher resolutions.

Another suggestion that is less important but would be nice to have is the ability to test the img2img setting on the image/mask that are loaded in the webui. What I mean is that you have to setup folders and an entire directory just to try to make adjustments and find optimal settings. Thanks again

**Comment by s9roll7** [comment]
Does that mean a function that only processes the first frame and then finishes?

**Comment by Echolink50** [comment]
No. Interrupting the process manually is no problem. It means to allow the EBsynth utility setting to be applied to the image/mask that has been uploaded to the webui

![ebsu](https://user-images.githubusercontent.com/54298963/224337995-ffdaab24-8a6b-40d1-8fc5-d8152e368971.jpg)

Like I said earlier, it would be nice to have but it's not that big of a deal. The face crop resolution size is far more important. Thanks

**Comment by Echolink50** [comment]
Thank you my friend

**Comment by s9roll7** [comment]
Fixed.

**Comment by Echolink50** [comment]
> Fixed.

Wow, you're fast. Will try it out later today when I get a chance

**Comment by s9roll7** [comment]
> Understood. I will try to implement it if I have a chance to refactor it.

I've added this feature as well, and it sure is handy
