### ISSUE TITLE
Movie path not found

### ISSUE THREAD

**Issue by SDstuffs** [s9roll7/ebsynth_utility#16]
Hi, this is really silly but for whatever reason, ebsynth is just refusing to pick up the video folder, for example, project dir is users\project, which it picks up just fine but user\project\movie with the video file in it and it just won't pick up for the movie file path. I have tried different folder locations but it just won't work for whatever reason.

**Comment by s9roll7** [comment]
I'm not sure what is going on here for a moment, but please set an empty directory for project_dir.

**Comment by s9roll7** [comment]
There seems to be some kind of misunderstanding.
Try putting the path of the movie you want to use in the "Original Movie Path" field.
(e.g. C:\my_video\test1.mp4)

**Comment by SDstuffs** [comment]
That's what I've been trying to say, it will not recognise the path I input. I created a new folder with the test in it C:\Users\P\Videos\movie\test1.mp4, filled out the dir fields, generate and again "original_movie_path not found", it must be something really stupid I'm missing.

**Comment by s9roll7** [comment]
Can't you simply create a folder named my_video directly under the C drive, put the mp4 file there, and specify the location?
C:\my_video\test1.mp4

**Comment by SDstuffs** [comment]
I tried that too, no luck. I'm really not sure what the problem is.

**Comment by Echolink50** [comment]
> I tried that too, no luck. I'm really not sure what the problem is.

Are you in the EBSynth tab? Not the EBSynth utility script in img2img tab. In the EBSynth tab there are 2 fields. One shoud be "C:\Users\P\Videos\movie" and the other "C:\Users\P\Videos\movie\test1.mp4"
