### ISSUE TITLE
auto tagging

### ISSUE THREAD

**Issue by AlexanderLJX** [s9roll7/ebsynth_utility#17]
Is it possible add an option to replace underscores with a space when auto tagging with deepbooru? Because the prompts with underscores are ineffective when used with the anime models. 

For example, "closed_eyes" doesn't seem to work whereas "closed eyes" works.

Or use the waifu diffusion 1.4 tagger https://github.com/toriato/stable-diffusion-webui-wd14-tagger

I know it's a simple fix but just stating the issue here.

**Comment by s9roll7** [comment]
Thank you for your suggestion.
I have never used a model that doesn't work with the danbooru tag, so I didn't notice.
It certainly seems better to have

**Comment by s9roll7** [comment]
Fixed.
