### ISSUE TITLE
[Bug] Mismatched directory names between stage 2 and 3

### ISSUE THREAD

**Issue by copejon** [s9roll7/ebsynth_utility#19]
Stage 2 generates directories called `video_frame` and `video_mask`. However, stage 3 expects a directory named `video_key`.  I believe this might be the same intended location as renaming `video_frame` -> `video_key` enables the recipe to move forward.

Related error, which occurs after stage 2 succeeds, and results from following stage 3 recipe:

```
C:\Users\GameBox\Pictures\Ebsynth\video_key not found
Generate key frames first.
```

**Comment by s9roll7** [comment]
The inputs and outputs for each stage are as follows

stage1
in : movie.mp4
out : video_frame / video_mask

stage2
in : video_frame / video_mask
out : video_key

stage3
in : video_key / video_mask
out : img2img_key

stage4 (optional)
in : img2img_key
out : img2img_upscale_key

stage5
in : img2img_upscale_key or img2img_key
out : .ebs

stage6
in : .ebs (img2img_key / video_mask / video_frame)
out : out-XXXXX

stage7
in : out-XXXXX
out : result.mp4

**Comment by copejon** [comment]
My mistake, closing
