### ISSUE TITLE
I ran to step 1 and printed out these information folders without generating video frames

### ISSUE THREAD

**Issue by miliPolo** [s9roll7/ebsynth_utility#21]
Skip frame extraction
'transparent-background' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
mask created

completed.

**Comment by s9roll7** [comment]
https://github.com/s9roll7/ebsynth_utility#installation
Have you done this step?

**Comment by s9roll7** [comment]
Try specifying a different project directory.
If you still reproduce it, please post all the logs from the console screen.

**Comment by miliPolo** [comment]
I installed it in the stablediffusion extension, and I'm having a hard time making sense of this gibberish

**Comment by miliPolo** [comment]
I suspect that I did not install transparen
<img width="938" alt="微信截图_20230315092747" src="https://user-images.githubusercontent.com/11912376/225180692-7273ce54-04ed-4ffd-a11b-ad5dcafe0b09.png">
t-background, and after I installed it the following error appears,here is the screenshot

**Comment by miliPolo** [comment]
It didn't work
<img width="789" alt="kdkdkdk" src="https://user-images.githubusercontent.com/11912376/225261531-eb35a24f-a437-470a-aa95-c766d7a54ebd.png">

**Comment by miliPolo** [comment]
I know the reason why, my original video was 25 frames per second, I changed it to 30 frames per second and it worked fine

**Comment by s9roll7** [comment]
#25

**Comment by scottttt29** [comment]
> Try specifying a different project directory. If you still reproduce it, please post all the logs from the console screen.
it works!
