### ISSUE TITLE
stage 1 issue, 

### ISSUE THREAD

**Issue by tcflying** [s9roll7/ebsynth_utility#22]
![WechatIMG724](https://user-images.githubusercontent.com/77509083/225404510-6109b340-0dbe-44ff-a326-0f7ed990a0aa.jpeg)
I have check the https://github.com/s9roll7/ebsynth_utility#installation, i see should install ebsynth, i download it. but there is no install programe, only .exe, how can i install? or i should place to somewhere?

**Comment by tcflying** [comment]
i have install transparent_background, still the error, after i change to clipseg. no error,

stage1

Skip frame extraction
mask created

completed.

but nothing been created.

**Comment by s9roll7** [comment]
I just created a new environment webui and installed this extension.
I had no problems in my environment

There is no need to install transparent_background separately in the first place. It is installed by itself as one of the dependent libraries when you install the extension.

**Comment by Pedroman1** [comment]
I have same problem I tried doing an entirely new enivronment and install and still get it
