### ISSUE TITLE
Project directory does not work

### ISSUE THREAD

**Issue by FinnT730** [s9roll7/ebsynth_utility#27]
Whenever I try to set the project path, whether it be in C:\ or on my D:\ drive, it does not work. I have this (see image) as the project path. Those double // were to test whether that would work or not.
In the second image, the console window, you can see how I tried it multiple times.

Is this an known issue, or is this me doing something wrong?

![image](https://user-images.githubusercontent.com/7442674/226112865-5ac19e4c-30d8-4a29-8046-d220c626daba.png)
![image](https://user-images.githubusercontent.com/7442674/226112930-2098c50f-19b6-40bf-a672-48db4ad449ff.png)

**Comment by s9roll7** [comment]
I don't know much about docker, but can you access the outside file system as is?

**Comment by FinnT730** [comment]
I found a way to access the right folders from Windows Explorer.
Docker is weird XD
