### ISSUE TITLE
Clarifications about controlnet, depth images, and clipseg

### ISSUE THREAD

**Issue by MikeMcDonald83** [s9roll7/ebsynth_utility#28]
I just have a couple questions about how these features are actually invoked.

controlnet -- Is each controlnet module invoked by ebsynth_utility in order? Does order even matter? In the readme, it shows the use of canny and normal modules. Can I use others modules like depth instead of using the depth_maps script? How about just canny? I tried using a depth module in controlnet, but it failed. This could be for any number of reasons, including my shoddy GPU. That's why I'm asking.

depth images (in video_key_depth) -- I am generating these manually before a run. Is that the correct workflow? How are these images actually used by your script?

clipseg -- are these actually used in image generation, or are they just used in .ebs file generation? If they are used in the actual img2img operation, how is it different than face crop? Also please explain face crop :)

**Comment by s9roll7** [comment]
As for using with controlnet, all ebsynth_utility is doing is overwriting input_image and weight.

As for video_key_depth, this was the mainstream method when there was no controlnet and is not a concern now.

clipseg is used only in stage1
