### ISSUE TITLE
add support for google colab

### ISSUE THREAD

**Issue by faisalhr1997** [s9roll7/ebsynth_utility#3]

**Comment by s9roll7** [comment]
The ebsynth this project is using is a windows gui app, so I think it would be difficult to achieve.
I have seen somewhere that it works with wine, but have not tried it.

**Comment by Yuya113256** [comment]
Thank you for the great extension.
So, is it still not possible to use this ebsynth_utility in the stable diffusion webui running on google colab?

**Comment by s9roll7** [comment]
It should only work on windows for now.
I don't think there is any way to run ebsynth on google colab, so I guess it's not worth considering

**Comment by s9roll7** [comment]
I fixed an implementation that only works on windows, so maybe it will work by any chance. (Not tested).

**Comment by Yuya113256** [comment]
I was able to confirm that it runs successfully on Colab!!
Thank you very much.
