### ISSUE TITLE
Possible to swap face not generated by img2img?

### ISSUE THREAD

**Issue by Echolink50** [s9roll7/ebsynth_utility#39]
So, I was wondering if it was possible to use swap a face from frames that are already made in a folder somewhere instead of the face created with img2img. I mean run the face detection and all that but swap another cropped face on each frame. Thanks

**Comment by s9roll7** [comment]
Technically it would be possible, but out of the scope of this extension. i have seen extension for face swap. You should probably use that one.

**Comment by Echolink50** [comment]
My idea was to us Thin plate to get a more consistent face and also to allow fewer key frames to be used for the body in EBsynth. Do you remember the name of the face swapper? Does it use yunet like your extension? Maybe there is something already in a config file for your extension that tells what directory to get the face from to paste? Thanks

**Comment by Echolink50** [comment]
Ok thanks
