### ISSUE TITLE
Alternate masks

### ISSUE THREAD

**Issue by djbielejeski** [s9roll7/ebsynth_utility#4]
Is there any plan to support other masking options besides transparent-background?

Love the plugin, btw, thanks for the great work!

**Comment by s9roll7** [comment]
Thanks for the suggestions.
If there is something that has good performance and does not conflict with the webui itself or the environment that major extensions depend on,  may be able to add it.

**Comment by djbielejeski** [comment]
I use this one with really good success

https://github.com/ThereforeGames/txt2mask

**Comment by s9roll7** [comment]
It's an interesting feature
i will try later

**Comment by s9roll7** [comment]
![clipseg](https://user-images.githubusercontent.com/118420657/221361845-ffebaab4-dd51-4c05-b263-f25824b7eb9b.png)
Added and selectable mask method.

**Comment by screan** [comment]
What specifically do the two sliders do? Thanks!

**Comment by s9roll7** [comment]
Mask Blur Kernel Size ... The larger the size, the smoother and blurrier the edges of the mask area will look.

Mask Threshold ... This value determines how much of the result detected by clipseg is included in the mask.
If you feel that unnecessary objects are masked, you may be able to cut them out better by increasing this value.

https://github.com/NielsRogge/Transformers-Tutorials/blob/master/CLIPSeg/Zero_shot_image_segmentation_with_CLIPSeg.ipynb
