### ISSUE TITLE
Why stage4 upscaled keyframe only?

### ISSUE THREAD

**Issue by supwang** [s9roll7/ebsynth_utility#49]
Hi:
Why stage4 upscaled keyframes only? The video original frames have not been upscaled?
If I use Ebsynth, I will got an error said frame resolution not match.

**Comment by phoenix747** [comment]
I also encountered this problem, after upscaled img, then Ebsynth util get error: source guide

**Comment by supwang** [comment]
> I also encountered this problem, after upscaled img, then Ebsynth util get error: source guide

Do not use upscale. :)

**Comment by phoenix747** [comment]
> I also encountered this problem, after upscaled img, then Ebsynth util get error: source guide

I figured out where the problem was. If you want to zoom in, it must be generated by reducing the size of img2img. You need to zoom back to the original size of the video to use this function.

**Comment by supwang** [comment]
> > I also encountered this problem, after upscaled img, then Ebsynth util get error: source guide
> 
> I figured out where the problem was. If you want to zoom in, it must be generated by reducing the size of img2img. You need to zoom back to the original size of the video to use this function.

Nice!
