### ISSUE TITLE
stage1 蒙版只能用CPU跑吗？

### ISSUE THREAD

**Issue by zwjman** [s9roll7/ebsynth_utility#55]
stage1

Skip frame extraction
Settings -> Mode=base, Device=cpu, Torchscript=disabled

python 3.10.8
cuda 12.0.89
cudnn 8.9.0
请问我需要做什么才能改成GPU运算

**Comment by s9roll7** [comment]
#52
(I haven't tried it myself)

**Comment by zwjman** [comment]
感谢您的回复，我再重新配置下环境试试，非常好的插件，谢谢

**Comment by Druchii236641237** [comment]
我使用CPU来运行, 结果爆内存了....  @s9roll7 希望作者能够更新下, 在第一阶段生成 MASK文件的时候, 如果改用GPU运算 因为我是 RTX4090

**Comment by Druchii236641237** [comment]
@ @s9roll7 @zwjman 勾选 JIT 就能使用GPU了, 如图 https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc17608e6-ad31-4522-ae93-868ed1a4cec1%2FUntitled.png?table=block&id=d7158a8c-c498-44a3-a0b2-e6066c3a0924&spaceId=e49deeaf-37a2-42f7-a433-549c1929ebf2&width=2000&userId=39165634-5d83-4358-9266-349ceb4e5255&cache=v2
