### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by GeekyGhost** [s9roll7/ebsynth_utility#7]
I made a slight change if that's okay? If you'd like I can send it to you. Though, you probably already can do way more than me based on your code. Pretty awesome job! Thank you for making this. 

![Screenshot 2023-03-04 145925](https://user-images.githubusercontent.com/111990299/222926274-374fda30-e5f0-4141-b72a-92c1a7ebc7cd.png)

**Comment by s9roll7** [comment]
I tried to implement this, but there seemed to be a problem
With gr.File and gr.Video, it seems that a copy is always made to a temporary folder the moment a file is selected.
In the case of these applications, as long as the path to the original file is known, the copy is completely meaningless.
Also, when large files are selected, the screen seems to freeze during copying.

**Comment by s9roll7** [comment]
I had a report that couldn't enter the path to the video, so I had to use this idea. Thank you.
