### ISSUE TITLE
about use gpu!!not bugs（关于如何开启gpu指南）

### ISSUE THREAD

**Issue by k186** [s9roll7/ebsynth_utility#85]
by those steps（work for my computer on win10）
1. install python 3.10.11
2. install pytorch `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` (我这里安装的是11.8版本)
3. install cuda 11.8  `https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows.exe`
![image](https://github.com/s9roll7/ebsynth_utility/assets/15086330/a343961b-15db-4c99-b311-18804a0f4067)

4. run ebsynth 
result 
![image](https://github.com/s9roll7/ebsynth_utility/assets/15086330/9b920dab-7363-4443-9712-e70f4c6f22c2)

**Comment by martinzhanggz** [comment]
doesn't work, installed CUDA and pytorch (same version) and stil runs on CPU......

**Comment by wuxin-hun** [comment]
我也是安装了CUDA和pytorch还是一样是CPU

**Comment by Ravius** [comment]
I've encountered same error. 
Updating\installing CUDA as global - works. 
But. I've catched same error after several videos, after several tries it just fallbacks to CPU, so i have to restart terminal -> cuda:0 again. 
I believe it falls back after one of latest steps (step 7 or step8). 

PS restarting cmd helps. so no big deal. ty

**Comment by aswirl4** [comment]
I am using the python managed by conda.
I install torch with " conda install ", then it works.
but i got the error "RuntimeError: CUDA error: out of memory"  in stage 1. I have no idea what to do with this.

**Comment by aswirl4** [comment]
> I am using the python managed by conda. I install torch with " conda install ", then it works. but i got the error "RuntimeError: CUDA error: out of memory" in stage 1. I have no idea what to do with this.

and I have no idea how to back to cpu.  what a sad.
