### ISSUE TITLE
TypeError: Script.run() missing 22 required positional arguments

### ISSUE THREAD

**Issue by jieran233** [s9roll7/ebsynth_utility#86]
TypeError: Script.run() missing 22 required positional arguments: 'project_dir', 'generation_test', 'mask_mode', 'inpaint_area', 'use_depth', 'img2img_repeat_count', 'inc_seed', 'auto_tag_mode', 'add_tag_to_head', 'add_tag_replace_underscore', 'is_facecrop', 'face_detection_method', 'face_crop_resolution', 'max_crop_size', 'face_denoising_strength', 'face_area_magnification', 'enable_face_prompt', 'face_prompt', 'controlnet_weight', 'controlnet_weight_for_face', 'disable_facecrop_lpbk_last_time', and 'use_preprocess_img'

**Comment by jieran233** [comment]
This is caused by Windows, check the owner and permissions of the working directory.

**Comment by Slowly-Grokking** [comment]
> This is caused by Windows, check the owner and permissions of the working directory.

how did you get this to work?  So far I don't seem to have modified the right permissions

**Comment by jieran233** [comment]
> > This is caused by Windows, check the owner and permissions of the working directory.
> 
> how did you get this to work? So far I don't seem to have modified the right permissions

The operation steps are as follows, which are only the steps summarized based on my personal experience, and I cannot guarantee its correctness and effectiveness. But you can have a try, in most cases there will be no problem doing this. Just in case, you can back up your work before proceeding.

![](https://s2.loli.net/2023/07/03/jzg6BoCy5qndU9s.png)

**Comment by Slowly-Grokking** [comment]
Thanks!

**Comment by KAKUmei3277** [comment]
Give permissions, still not working

**Comment by alimalls** [comment]
没用，换几个版本还是同样的问题
